-- ==============================================================================
-- FAQ institucional UTCJ para el chatbot
-- Fuente principal: https://www.utcj.edu.mx y páginas públicas enlazadas.
-- ==============================================================================

INSERT INTO public.chatbot_faq_entries (
  id,
  category,
  question,
  answer,
  keywords,
  priority,
  status,
  source,
  requires_handoff
)
VALUES
  (
    '00000000-0000-4000-8000-000000000701',
    'utcj_general',
    'Donde esta ubicada la UTCJ',
    'La Universidad Tecnologica de Ciudad Juarez esta ubicada en Av. Universidad Tecnologica No. 3051, Col. Lote Bravo II, Cd. Juarez, Chihuahua, C.P. 32695.',
    ARRAY['direccion', 'ubicacion', 'domicilio', 'lote bravo', 'donde esta', 'mapa'],
    30,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000702',
    'utcj_general',
    'Cual es la mision de la UTCJ',
    'La UTCJ forma profesionistas lideres y competitivos mediante innovacion academica, vinculacion con el sector productivo y responsabilidad social, promoviendo valores como respeto a la dignidad, sustentabilidad y etica profesional.',
    ARRAY['mision', 'institucional', 'quienes somos', 'utcj'],
    31,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000703',
    'utcj_general',
    'Cual es la vision de la UTCJ',
    'La vision de la UTCJ es ser la Universidad Tecnologica numero uno en Mexico formando talento integral que genere desarrollo para la comunidad.',
    ARRAY['vision', 'institucional', 'futuro', 'utcj'],
    32,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000704',
    'utcj_general',
    'Cuales son los valores de la UTCJ',
    'Los valores publicados por la UTCJ incluyen innovacion, bien comun, integridad, liderazgo, sustentabilidad, responsabilidad social, sostenibilidad, calidad, dignidad de la persona, inclusion y equidad.',
    ARRAY['valores', 'integridad', 'inclusion', 'equidad', 'calidad'],
    33,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000705',
    'accesos',
    'Donde entro al SISE',
    'El acceso a SISE aparece como enlace rapido del sitio UTCJ y apunta al portal de alumnos: https://alumnos.utcj.edu.mx. Si no tienes usuario o contrasena, Servicios Escolares indica acudir a la Subdireccion de Sistemas con credencial escolar vigente.',
    ARRAY['sise', 'portal alumnos', 'alumnos utcj', 'referencia bancaria', 'usuario sise'],
    10,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000706',
    'accesos',
    'Donde entro al correo institucional',
    'El sitio oficial de UTCJ enlaza el Correo Institucional desde sus accesos rapidos. Puedes entrar desde https://login.utcj.edu.mx.',
    ARRAY['correo institucional', 'email', 'login utcj', 'correo utcj'],
    11,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000707',
    'oferta_academica',
    'Como funciona el modelo de estudios de la UTCJ',
    'El modelo UTCJ tiene dos etapas: primero TSU durante 6 cuatrimestres, con formacion practica, talleres, laboratorios y estadias; despues puedes continuar 4 cuatrimestres mas para obtener Ingenieria o Licenciatura.',
    ARRAY['modelo', 'modelo de estudios', 'tsu', 'ingenieria', 'licenciatura', 'cuatrimestres'],
    20,
    'published',
    'https://www.utcj.edu.mx/modelo-de-estudios/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000708',
    'oferta_academica',
    'Que ventajas tiene el modelo de estudios UTCJ',
    'El modelo ofrece dos titulos en un solo plan de estudios, experiencia practica desde el primer dia, estadias en empresas y formacion adaptada a necesidades reales de la industria.',
    ARRAY['ventajas', 'doble titulacion', 'practica', 'industria', 'estadias'],
    21,
    'published',
    'https://www.utcj.edu.mx/modelo-de-estudios/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000709',
    'oferta_academica',
    'Que carreras TSU ofrece la UTCJ',
    'En la oferta TSU publicada aparecen: Contaduria, Mercadotecnia, Operaciones Logisticas y Comercio Exterior, Manufactura de Semiconductores, Nanotecnologia, Procesos Productivos, Infraestructuras de Redes Digitales, Desarrollo de Software Multiplataforma, Automatizacion, Robotica, Sistemas de Manufactura Flexible, Energia Turbo-solar y Paramedico.',
    ARRAY['tsu', 'carreras tsu', 'oferta academica', 'software', 'semiconductores', 'paramedico'],
    22,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000710',
    'oferta_academica',
    'Que ingenierias ofrece la UTCJ',
    'En la oferta publicada aparecen Ingenieria en Logistica Internacional, Semiconductores, Mantenimiento Industrial, Nanotecnologia, Industrial, Tecnologias de la Informacion e Innovacion Digital, Mecatronica y Energia y Desarrollo Sostenible.',
    ARRAY['ingenierias', 'ingenieria', 'logistica', 'mecatronica', 'industrial', 'tiid', 'energia'],
    23,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000711',
    'oferta_academica',
    'Que licenciaturas ofrece la UTCJ',
    'En la oferta publicada aparecen Licenciatura en Contaduria, Negocios y Mercadotecnia, Proteccion Civil y Terapia Fisica.',
    ARRAY['licenciaturas', 'licenciatura', 'contaduria', 'negocios', 'mercadotecnia', 'proteccion civil', 'terapia fisica'],
    24,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000712',
    'oferta_academica',
    'Que posgrados ofrece la UTCJ',
    'En la oferta publicada aparecen Maestria en Logistica y Negocios Sustentables, Maestria en Ingenieria de Sistemas Industriales Sustentables y Especialidad en Semiconductores.',
    ARRAY['posgrado', 'maestria', 'maestrias', 'especialidad', 'semiconductores'],
    25,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000713',
    'servicios_escolares',
    'Que hace Servicios Escolares',
    'Servicios Escolares atiende aspirantes y estudiantes en procesos de inscripcion, reinscripcion y tramites escolares. Tambien expide credenciales, constancias, historiales, certificados, gestiona titulacion y equivalencias.',
    ARRAY['servicios escolares', 'tramites escolares', 'inscripcion', 'reinscripcion', 'constancias', 'certificados'],
    40,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000714',
    'servicios_escolares',
    'Como solicito constancia historial certificado o credencial',
    'Para solicitar documentos, primero paga en cajas del Edificio F en horario de 9:00 a.m. a 6:00 p.m.; despues acude a Servicios Escolares con comprobante de Finanzas y credencial escolar u otra identificacion oficial vigente.',
    ARRAY['constancia', 'historial academico', 'certificado parcial', 'credencial', 'documentos', 'cajas'],
    41,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000715',
    'servicios_escolares',
    'Cuanto cuestan los documentos escolares',
    'La pagina de Servicios Escolares publica estos costos: constancia de estudios $39, historial academico $65, certificado parcial $262 y credencial escolar $65. Verifica vigencia directamente con Servicios Escolares antes de pagar.',
    ARRAY['costos', 'precio', 'constancia', 'historial', 'certificado', 'credencial'],
    42,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000716',
    'servicios_escolares',
    'Cuales son los requisitos de reinscripcion',
    'Para reinscripcion se publican como requisitos: acreditar materias del periodo anterior, acreditar actividad extraescolar cuando aplique, no tener adeudos bibliotecarios, tener documentos requeridos entregados y realizar el pago bancario en fechas indicadas.',
    ARRAY['reinscripcion', 'reinscripciones', 'requisitos reinscripcion', 'adeudos', 'referencia bancaria'],
    43,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000717',
    'servicios_escolares',
    'Como imprimo mi formato de pago de reinscripcion',
    'Entra a https://alumnos.utcj.edu.mx con usuario y contrasena, ve a Menu Principal / Finanzas / Referencia Bancaria, presiona imprimir y realiza el pago con tu formato. La referencia es individual y no debe compartirse.',
    ARRAY['formato de pago', 'referencia bancaria', 'finanzas', 'reinscripcion', 'pago'],
    44,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000718',
    'servicios_escolares',
    'Como solicito reingreso a la UTCJ',
    'Si causaste baja, reprobaste o estuviste fuera un cuatrimestre, solicita reingreso desde SISE en Menu principal / Escolares / Reingresos. Puedes elegir misma carrera, cambio de carrera, area o turno. Las fechas se consultan en calendario escolar.',
    ARRAY['reingreso', 'baja', 'cambio de carrera', 'cambio de turno', 'sise'],
    45,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000719',
    'servicios_escolares',
    'Que hago si no aparezco activo en SISE',
    'Servicios Escolares indica estar pendiente del correo institucional o contactar a escolares@utcj.edu.mx si no apareces activo en SISE en el tiempo estimado despues del pago.',
    ARRAY['no aparezco activo', 'activo en sise', 'escolares', 'correo institucional'],
    46,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000720',
    'servicios_escolares',
    'Que es continuidad de estudios',
    'Continuidad de Estudios esta dirigida a estudiantes que concluyen TSU y desean ingresar a Ingenieria o Licenciatura.',
    ARRAY['continuidad', 'continuidad de estudios', 'tsu a ingenieria', 'tsu a licenciatura'],
    47,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-escolares/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000721',
    'becas',
    'Que becas internas ofrece la UTCJ',
    'El Departamento de Becas gestiona becas internas academicas, economicas, deportivas, culturales, alimenticias, de transporte, familiares y municipales. Normalmente se tramitan al inicio de cada cuatrimestre, segun convocatoria y disponibilidad.',
    ARRAY['becas', 'beca interna', 'becas internas', 'apoyo economico'],
    50,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000722',
    'becas',
    'Como funciona la beca academica',
    'La beca academica es condonacion de inscripcion para alumnos de alto rendimiento. La pagina publica rangos de descuento de 100%, 75%, 50% y 25% segun promedio. El tramite suele realizarse semanas antes de finalizar el cuatrimestre por SISE.',
    ARRAY['beca academica', 'promedio', 'alto rendimiento', 'descuento inscripcion'],
    51,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000723',
    'becas',
    'Como funciona la beca familiar',
    'La beca familiar ofrece condonacion del 50% en inscripcion y colegiatura para estudiantes UTCJ con familiares directos inscritos en la institucion. Se solicita al inicio de cada cuatrimestre durante reinscripcion.',
    ARRAY['beca familiar', 'familiares', '50%', 'colegiatura', 'inscripcion'],
    52,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000724',
    'becas',
    'Como funciona la beca trabajador',
    'La beca trabajador ofrece condonacion del 100% en inscripcion y colegiatura para estudiantes con familiares directos que sean trabajadores activos de la UTCJ, conforme a convocatoria vigente.',
    ARRAY['beca trabajador', 'trabajador utcj', '100%', 'familiares trabajadores'],
    53,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000725',
    'becas',
    'Como funciona la beca deportiva y cultural',
    'La beca deportiva y cultural puede condonar 50% o 100% de inscripcion y colegiatura para estudiantes que formen parte de grupos representativos deportivos o culturales, segun convocatoria vigente.',
    ARRAY['beca deportiva', 'beca cultural', 'deporte', 'cultura', 'representativos'],
    54,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000726',
    'becas',
    'Como funciona la beca incluyente',
    'La beca incluyente ofrece condonacion del 50% en inscripcion y colegiatura para estudiantes con discapacidad motriz, auditiva, de lenguaje o visual comprobable mediante diagnostico medico.',
    ARRAY['beca incluyente', 'discapacidad', 'inclusion', 'diagnostico medico'],
    55,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000727',
    'becas',
    'Como funciona la beca continuidad',
    'La beca continuidad apoya a estudiantes que cursaron estancias de TSU y continuan a Ingenieria o Licenciatura. La pagina publica descuentos de 50% o 25% segun promedio y convocatoria.',
    ARRAY['beca continuidad', 'continuidad', 'tsu', 'ingenieria', 'licenciatura'],
    56,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000728',
    'becas',
    'Como funciona la beca transporte',
    'La beca transporte da traslado gratuito para estudiantes inscritos en turno matutino que comprueben domicilio en el Valle de Juarez, desde Loma Blanca hasta Praxedis G. Guerrero. Se solicita al inicio del cuatrimestre.',
    ARRAY['beca transporte', 'transporte', 'valle de juarez', 'loma blanca', 'praxedis'],
    57,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000729',
    'becas',
    'Como funciona la beca alimenticia',
    'La beca alimenticia provee alimento diario en cafeteria para estudiantes canalizados por Servicio Medico. Esta sujeta a disponibilidad y se solicita durante el cuatrimestre.',
    ARRAY['beca alimenticia', 'comida', 'cafeteria', 'servicio medico'],
    58,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000730',
    'becas',
    'Donde contacto al Departamento de Becas',
    'El Departamento de Becas publica el correo becas@utcj.edu.mx, Edificio F y telefono 656 649 0600 ext. 3926.',
    ARRAY['contacto becas', 'becas@utcj.edu.mx', 'edificio f', '3926'],
    59,
    'published',
    'https://www.utcj.edu.mx/departamento-de-becas/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000731',
    'biblioteca',
    'Que servicios ofrece la biblioteca',
    'Biblioteca ofrece prestamo externo, consulta interna, prestamo interbibliotecario, bases de datos, catalogos electronicos, articulos, publicaciones, informacion del INEGI, internet, espacios de estudio, referencia, computo, copias e impresiones.',
    ARRAY['biblioteca', 'servicios bibliotecarios', 'prestamo', 'bases de datos', 'inegi', 'copias'],
    60,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-bibliotecarios/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000732',
    'biblioteca',
    'Cual es el horario de biblioteca',
    'El horario publicado de biblioteca es lunes a viernes de 7:00 a.m. a 9:30 p.m.',
    ARRAY['horario biblioteca', 'biblioteca horario', '7:00', '9:30'],
    61,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-bibliotecarios/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000733',
    'biblioteca',
    'Como entro a la biblioteca digital',
    'Para alumnos, el usuario de Biblioteca Digital es la matricula y la contrasena es UTCJ_matricula. Para personal docente y administrativo, usuario y contrasena usan UTCJ_numero de empleado.',
    ARRAY['biblioteca digital', 'usuario biblioteca', 'contraseña biblioteca', 'matricula', 'libros electronicos'],
    62,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-bibliotecarios/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000734',
    'biblioteca',
    'Cuantos materiales puedo pedir prestados en biblioteca',
    'El prestamo externo para comunidad UTCJ permite hasta 3 materiales por 3 dias. La consulta interna en sala esta abierta dentro de las instalaciones.',
    ARRAY['prestamo biblioteca', 'materiales', 'libros', '3 dias', 'prestamo externo'],
    63,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-bibliotecarios/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000735',
    'biblioteca',
    'Donde contacto a biblioteca',
    'Biblioteca publica el correo biblioteca@utcj.edu.mx, telefono 656 649 0600 ext. 3821 y 3818. Tambien aparece Edificio F y, para jefatura, Edificio D segundo piso.',
    ARRAY['contacto biblioteca', 'biblioteca@utcj.edu.mx', '3821', '3818'],
    64,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-bibliotecarios/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000736',
    'estadias',
    'Que son las estadias en la UTCJ',
    'Las estadias son una actividad curricular obligatoria donde el estudiante desarrolla un proyecto real en empresa, aplica conocimientos practicos para titularse y recibe supervision dual de universidad y empresa.',
    ARRAY['estadias', 'estadía', 'empresa', 'proyecto real', 'titulacion'],
    70,
    'published',
    'https://www.utcj.edu.mx/departamento-de-enlace-empresarial-y-estadias/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000737',
    'estadias',
    'Cuantas horas de estadia debo cumplir',
    'La pagina publica 525 horas para TSU, 510 para Contaduria y 480 horas para Ingenierias/Licenciaturas excepto area de la salud.',
    ARRAY['horas estadia', '525', '510', '480', 'contaduria'],
    71,
    'published',
    'https://www.utcj.edu.mx/departamento-de-enlace-empresarial-y-estadias/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000738',
    'estadias',
    'Como inicio mi proceso de estadia',
    'Como alumno, ingresa a SISE Alumnos, registra tu curriculum, visualiza empresas y proyectos disponibles y da seguimiento al estado de tu tramite.',
    ARRAY['proceso estadia', 'curriculum', 'empresas', 'proyectos', 'sise alumnos'],
    72,
    'published',
    'https://www.utcj.edu.mx/departamento-de-enlace-empresarial-y-estadias/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000739',
    'estadias',
    'Donde contacto a Estadias',
    'El area de Estadias publica como contacto a Nidia Fernandez, correo nidia_fernandez@utcj.edu.mx, Edificio F, telefono 656 649 0600 ext. 3836.',
    ARRAY['contacto estadias', 'nidia fernandez', 'nidia_fernandez@utcj.edu.mx', '3836'],
    73,
    'published',
    'https://www.utcj.edu.mx/departamento-de-enlace-empresarial-y-estadias/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000740',
    'movilidad',
    'Que es movilidad estudiantil UTCJ',
    'Movilidad Estudiantil ofrece oportunidades de experiencias academicas y culturales en otros paises, incluyendo estancias cortas, intercambios academicos, practicas profesionales internacionales y convenios con instituciones.',
    ARRAY['movilidad', 'intercambio', 'internacionalizacion', 'practicas internacionales'],
    80,
    'published',
    'https://www.utcj.edu.mx/movilidad-estudiantil/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000741',
    'movilidad',
    'Como me entero de convocatorias de movilidad',
    'Las convocatorias de movilidad se difunden oficialmente por correo institucional. Tambien puedes solicitar informacion al correo samantha_concha@utcj.edu.mx.',
    ARRAY['convocatoria movilidad', 'correo institucional', 'intercambio', 'samantha_concha'],
    81,
    'published',
    'https://www.utcj.edu.mx/movilidad-estudiantil/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000742',
    'movilidad',
    'Que convenios de movilidad menciona la UTCJ',
    'La pagina de Movilidad menciona convenios vigentes con University of Regina en Saskatchewan, Canada, y Alamo College en San Antonio, Texas.',
    ARRAY['convenios movilidad', 'canada', 'regina', 'alamo college', 'texas'],
    82,
    'published',
    'https://www.utcj.edu.mx/movilidad-estudiantil/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000743',
    'movilidad',
    'Cuando abre la convocatoria para Canada',
    'La pagina de Movilidad indica que la apertura de convocatoria para la beca de Canada se realiza cada mes de febrero.',
    ARRAY['canada', 'beca canada', 'febrero', 'convocatoria canada'],
    83,
    'published',
    'https://www.utcj.edu.mx/movilidad-estudiantil/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000744',
    'movilidad',
    'Donde contacto a Movilidad Estudiantil',
    'Movilidad Estudiantil publica como contacto a Lic. Samantha Edith Concha Delgado, correo samantha_concha@utcj.edu.mx, Edificio A segundo piso, telefono 656 649 0600 ext. 3883.',
    ARRAY['contacto movilidad', 'samantha concha', 'samantha_concha@utcj.edu.mx', '3883'],
    84,
    'published',
    'https://www.utcj.edu.mx/movilidad-estudiantil/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000745',
    'servicio_medico',
    'Que hace Servicio Medico UTCJ',
    'Servicio Medico promueve cultura de salud mediante atencion primaria, estilos de vida saludables, urgencias medicas, canalizacion a nutricion, psicologia u hospital, deteccion de diabetes e hipertension y jornadas preventivas.',
    ARRAY['servicio medico', 'salud', 'urgencias', 'nutricion', 'diabetes', 'hipertension'],
    90,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-medicos/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000746',
    'servicio_medico',
    'Servicio Medico ayuda con seguro facultativo',
    'Si. Servicio Medico apoya a estudiantes con el tramite y verificacion de vigencia del seguro facultativo del Instituto Mexicano del Seguro Social.',
    ARRAY['seguro facultativo', 'imss', 'servicio medico', 'vigencia seguro'],
    91,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-medicos/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000747',
    'servicio_medico',
    'Donde contacto a Servicio Medico',
    'Servicio Medico publica el correo servicio_medico@utcj.edu.mx, Edificio C y telefono 656 649 0600 ext. 3844.',
    ARRAY['contacto servicio medico', 'servicio_medico@utcj.edu.mx', 'edificio c', '3844'],
    92,
    'published',
    'https://www.utcj.edu.mx/departamento-de-servicios-medicos/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000748',
    'psicopedagogico',
    'Que hace Apoyo Psicopedagogico',
    'La Unidad de Apoyo Psicopedagogico brinda acompanamiento integral con orientacion psicologica, academica y personal para favorecer bienestar emocional, aprendizaje, desarrollo humano, permanencia y exito universitario.',
    ARRAY['psicopedagogico', 'psicologia', 'orientacion', 'bienestar emocional', 'apoyo academico'],
    100,
    'published',
    'https://www.utcj.edu.mx/unidad-de-apoyo-psicopedagogico/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000749',
    'psicopedagogico',
    'En que me puede apoyar Psicopedagogia',
    'Puede apoyar en situaciones emocionales, estres, ansiedad, estrategias de estudio, organizacion del tiempo, concentracion, motivacion, necesidades educativas especificas, adaptacion universitaria y habilidades socioemocionales.',
    ARRAY['estres', 'ansiedad', 'estrategias de estudio', 'organizacion del tiempo', 'adaptacion universitaria'],
    101,
    'published',
    'https://www.utcj.edu.mx/unidad-de-apoyo-psicopedagogico/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000750',
    'psicopedagogico',
    'Donde contacto a Psicopedagogia',
    'La Unidad de Apoyo Psicopedagogico publica como contacto a Lic. Juan Javier Hernandez, correo juan_jhernandez@utcj.edu.mx, Edificios H y Q, telefono 656 649 0600 ext. 3804 y 3808.',
    ARRAY['contacto psicopedagogia', 'juan_jhernandez@utcj.edu.mx', '3804', '3808', 'edificio h', 'edificio q'],
    102,
    'published',
    'https://www.utcj.edu.mx/unidad-de-apoyo-psicopedagogico/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000751',
    'calendario',
    'Donde veo el calendario escolar',
    'El calendario escolar 2025-2026 esta publicado en https://www.utcj.edu.mx/calendario-escolar/ e incluye vacaciones, asuetos y fechas limite para tramites.',
    ARRAY['calendario escolar', 'fechas importantes', 'vacaciones', 'asuetos', 'tramites'],
    110,
    'published',
    'https://www.utcj.edu.mx/calendario-escolar/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000752',
    'canales',
    'Donde veo noticias eventos y convocatorias',
    'El sitio UTCJ tiene enlaces rapidos a Noticias, Eventos y Convocatorias. Tambien ofrece suscripcion para recibir avisos, noticias, convocatorias, eventos y mas por correo.',
    ARRAY['noticias', 'eventos', 'convocatorias', 'avisos', 'suscripcion'],
    120,
    'published',
    'https://www.utcj.edu.mx/',
    false
  ),
  (
    '00000000-0000-4000-8000-000000000753',
    'soporte',
    'Donde pido soporte tecnico institucional',
    'El sitio UTCJ lista Sistemas como Soporte Tecnico dentro de servicios y recursos institucionales internos. Para problemas de acceso a SISE, Servicios Escolares indica acudir a Subdireccion de Sistemas con credencial escolar vigente.',
    ARRAY['soporte tecnico', 'sistemas', 'problemas sise', 'subdireccion de sistemas'],
    130,
    'published',
    'https://www.utcj.edu.mx/',
    true
  )
ON CONFLICT (id) DO UPDATE
SET category = EXCLUDED.category,
    question = EXCLUDED.question,
    answer = EXCLUDED.answer,
    keywords = EXCLUDED.keywords,
    priority = EXCLUDED.priority,
    status = EXCLUDED.status,
    source = EXCLUDED.source,
    requires_handoff = EXCLUDED.requires_handoff,
    updated_at = now();
