insert into public.chatbot_faq_entries
  (category, question, answer, keywords, priority, status, source, requires_handoff)
values
  ('Citas', '¿Cómo solicito una cita con mi tutor?', 'Entra a Citas con Tutor, revisa los horarios disponibles, selecciona el bloque que te convenga y explica brevemente el motivo. Tu tutor podrá confirmar o actualizar la cita.', array['cita', 'agendar', 'tutor', 'horario'], 10, 'published', 'Guía operativa SyncUT', false),
  ('Citas', '¿Puedo cancelar o cambiar una cita?', 'Sí. Abre Citas con Tutor y localiza tu cita activa. Cancélala con anticipación y solicita otra disponibilidad. Si la cita ya comenzó, comunícate directamente con tu tutor.', array['cancelar', 'cambiar', 'reprogramar', 'cita'], 20, 'published', 'Guía operativa SyncUT', false),
  ('Justificaciones', '¿Cómo registro una justificación?', 'Abre Justificaciones, captura el motivo y las fechas correspondientes, y adjunta evidencia legible si aplica. Después podrás consultar el estado y responder si el tutor solicita más información.', array['justificacion', 'falta', 'evidencia', 'ausencia'], 10, 'published', 'Guía operativa SyncUT', false),
  ('Justificaciones', '¿Qué evidencia puedo adjuntar?', 'Adjunta únicamente documentos relacionados con tu ausencia y evita compartir información sensible innecesaria. El archivo debe ser legible. El tutor puede pedir aclaraciones antes de resolver.', array['archivo', 'documento', 'evidencia', 'comprobante'], 20, 'published', 'Guía operativa SyncUT', false),
  ('Incidencias', '¿Cómo reporto un problema académico?', 'Entra a Reportes Incidencias, elige área, categoría y prioridad, describe qué ocurrió con datos concretos y envía el reporte. Podrás seguir su estado y leer comentarios desde el mismo módulo.', array['incidencia', 'problema', 'reporte', 'queja'], 10, 'published', 'Guía operativa SyncUT', false),
  ('Incidencias', '¿Qué hago si mi incidencia es urgente?', 'Registra la incidencia con prioridad alta y explica claramente el impacto. Si existe riesgo inmediato para una persona, no esperes al chatbot: contacta a tu tutor o a los servicios de emergencia correspondientes.', array['urgente', 'emergencia', 'riesgo', 'incidencia'], 20, 'published', 'Guía operativa SyncUT', true),
  ('Cuenta', 'No puedo iniciar sesión', 'Verifica tu correo institucional y contraseña. Usa Recuperar contraseña en la pantalla de acceso si es necesario. Nunca compartas tu contraseña. Si el problema continúa, solicita apoyo administrativo.', array['login', 'sesion', 'contraseña', 'acceso', 'cuenta'], 10, 'published', 'Guía operativa SyncUT', false),
  ('Notificaciones', '¿Dónde consulto mis avisos?', 'Abre Notificaciones desde el menú. Allí encontrarás cambios en citas, justificaciones, incidencias y avisos de tu equipo tutorial. Revisa también tu correo institucional.', array['notificacion', 'aviso', 'correo', 'mensaje'], 10, 'published', 'Guía operativa SyncUT', false),
  ('Privacidad', '¿La IA puede tomar decisiones académicas?', 'No. Lumi solo ofrece orientación y puede resumir información publicada. La aprobación de justificaciones, atención de incidencias y cualquier decisión académica corresponde al tutor o al personal autorizado.', array['ia', 'decision', 'aprobar', 'privacidad'], 10, 'published', 'Política del asistente SyncUT', false),
  ('Soporte', 'Quiero hablar con una persona', 'Claro. Explica brevemente el caso y comunícate con tu tutor desde los canales institucionales. Para asuntos sensibles o decisiones académicas, la atención humana siempre tiene prioridad.', array['persona', 'humano', 'tutor', 'ayuda', 'soporte'], 10, 'published', 'Guía operativa SyncUT', true)
on conflict do nothing;
