import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { SubmitButton } from "@/components/forms/submit-button";
import { requireProfile } from "@/lib/auth/session";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Delivery = { id:string; status:"sent"|"received"; sent_at:string; received_at:string|null; justification:{folio:string;title:string;category:string;start_date:string;end_date:string;review_notes:string|null;student:{full_name:string|null;email:string}|null}|null; team:{name:string}|null; sender:{full_name:string|null;email:string}|null };

async function acknowledge(formData: FormData) { "use server"; const profile=await requireProfile(); if(profile.role!=="teacher") redirect("/dashboard"); const id=String(formData.get("delivery_id")??""); const supabase=await createSupabaseServerClient(); const {error}=await supabase.rpc("acknowledge_justification_delivery" as "get_teacher_directory", {p_delivery_id:id} as never); if(error) redirect(`/docente?error=${encodeURIComponent(error.message)}`); revalidatePath("/docente"); redirect("/docente?received=true"); }

export default async function TeacherInbox({searchParams}:{searchParams:Promise<{received?:string;error?:string}>}) {
  const profile=await requireProfile(); if(profile.role!=="teacher") redirect("/dashboard"); const params=await searchParams; const supabase=await createSupabaseServerClient();
  const {data}=await supabase.from("justification_teacher_deliveries" as "notifications").select("id,status,sent_at,received_at,justification:justifications!inner(folio,title,category,start_date,end_date,review_notes,student:profiles!justifications_student_id_fkey(full_name,email)),team:tutor_teams!inner(name),sender:profiles!justification_teacher_deliveries_sent_by_fkey(full_name,email)").order("sent_at" as "created_at",{ascending:false});
  const deliveries=(data??[]) as unknown as Delivery[]; const pending=deliveries.filter((item)=>item.status==="sent");
  return <div className="mx-auto max-w-5xl space-y-6"><header><p className="text-xs font-semibold uppercase tracking-wider text-primary">Recepción docente</p><h1 className="mt-2 text-3xl font-bold text-on-surface">Bandeja docente</h1><p className="mt-2 text-sm text-on-surface-variant">Solo aparecen documentos aprobados y comunicaciones enviadas formalmente por un tutor.</p></header>
  {params.received?<p className="rounded border border-tertiary bg-tertiary-container p-3 text-sm text-on-tertiary-container">Recepción confirmada. El flujo quedó cerrado.</p>:null}{params.error?<p className="rounded border border-error bg-error-container p-3 text-sm text-on-error-container">{params.error}</p>:null}
  <section className="grid gap-3 sm:grid-cols-3"><div className="rounded-lg border border-outline-variant bg-surface-container p-4"><p className="text-xs text-on-surface-variant">Pendientes de recibir</p><p className="mt-2 text-3xl font-black text-primary">{pending.length}</p></div><div className="rounded-lg border border-outline-variant bg-surface-container p-4"><p className="text-xs text-on-surface-variant">Recibidos</p><p className="mt-2 text-3xl font-black text-on-surface">{deliveries.length-pending.length}</p></div></section>
  <section className="space-y-3">{deliveries.length===0?<p className="rounded-lg border border-outline-variant bg-surface-container p-6 text-sm text-on-surface-variant">No tienes justificantes enviados por tutores.</p>:deliveries.map((item)=><article key={item.id} className="rounded-lg border border-outline-variant bg-surface-container p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-semibold text-primary">{item.justification?.folio} · {item.team?.name}</p><h2 className="mt-1 text-lg font-bold text-on-surface">{item.justification?.title}</h2><p className="mt-1 text-xs text-on-surface-variant">Alumno: {item.justification?.student?.full_name??item.justification?.student?.email} · {item.justification?.start_date} a {item.justification?.end_date}</p></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status==='received'?'bg-tertiary-container text-on-tertiary-container':'bg-primary-container text-on-primary-container'}`}>{item.status==='received'?'Recibido':'Requiere confirmación'}</span></div>{item.justification?.review_notes?<p className="mt-4 rounded bg-surface p-3 text-sm text-on-surface-variant"><b className="text-on-surface">Resolución del tutor:</b> {item.justification.review_notes}</p>:null}<p className="mt-3 text-xs text-on-surface-variant">Enviado por {item.sender?.full_name??item.sender?.email} el {new Date(item.sent_at).toLocaleString('es-MX')}</p>{item.status==='sent'?<form action={acknowledge} className="mt-4"><input type="hidden" name="delivery_id" value={item.id}/><SubmitButton className="rounded bg-primary-container px-4 py-2 text-sm font-bold text-on-primary-container" pendingLabel="Confirmando...">Confirmar recepción y cerrar</SubmitButton></form>:null}</article>)}</section></div>;
}
